sudo: required
language: node_js
node_js:
  - "10.1.0"
dist: trusty
cache:
  directories:
    - node_modules
install:
  - "npm install"
script:
  - "npm run test"
deploy:
  on: 
    branch: master
  provider: npm
  email: "gpevnev1@gmail.com"
  api_key: $API
